# Generated by Django 5.2 on 2025-05-30 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(default='Maruti Suzuki', max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('variant', models.CharField(max_length=100)),
                ('vin', models.CharField(max_length=50)),
                ('fuel_type', models.CharField(max_length=20)),
                ('transmission', models.CharField(max_length=20)),
                ('engine_cc', models.IntegerField()),
                ('engine_type', models.CharField(max_length=100)),
                ('bhp', models.CharField(max_length=20)),
                ('airbags', models.IntegerField()),
                ('mileage_kmpl', models.FloatField()),
                ('ncap_rating', models.CharField(blank=True, max_length=20, null=True)),
                ('num_keys', models.IntegerField()),
                ('inspection_date', models.DateField()),
                ('inspected_by', models.CharField(max_length=100)),
                ('health_score', models.FloatField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CarPDI.customer')),
            ],
        ),
        migrations.CreateModel(
            name='TyreCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=50)),
                ('brand', models.CharField(max_length=50)),
                ('condition', models.CharField(max_length=50)),
                ('manufacturing_date', models.CharField(max_length=20)),
                ('remaining_life_percent', models.FloatField()),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CarPDI.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='SystemCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('status', models.CharField(default='All OK', max_length=20)),
                ('issues', models.IntegerField(default=0)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CarPDI.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='RubberComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=100)),
                ('condition', models.CharField(max_length=50)),
                ('recommendation', models.CharField(max_length=100)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CarPDI.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='PerformanceCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=20)),
                ('recommendation', models.CharField(max_length=100)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CarPDI.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='PaintFinish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=100)),
                ('repainted', models.BooleanField()),
                ('condition', models.CharField(max_length=50)),
                ('action', models.CharField(max_length=100)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CarPDI.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='OBDReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avg_city_running_kms', models.IntegerField()),
                ('pre_delivery_odo_kms', models.IntegerField()),
                ('current_odo_kms', models.IntegerField()),
                ('obd_running_kms', models.IntegerField()),
                ('obd_tampering', models.BooleanField()),
                ('vehicle', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='CarPDI.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='NetworkSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=100)),
                ('remark', models.CharField(max_length=200)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CarPDI.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='InteriorComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Floor', 'Floor'), ('Plastic', 'Plastic'), ('Fabric', 'Fabric')], max_length=50)),
                ('area', models.CharField(max_length=100)),
                ('condition', models.CharField(max_length=50)),
                ('recommendation', models.CharField(max_length=100)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CarPDI.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='GlassComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=50)),
                ('condition', models.CharField(max_length=50)),
                ('recommendation', models.CharField(max_length=100)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CarPDI.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='FlushGap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=100)),
                ('operation', models.CharField(max_length=50)),
                ('observation_gap', models.CharField(max_length=50)),
                ('action', models.CharField(max_length=100)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CarPDI.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='FluidLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('in_range', models.BooleanField()),
                ('contamination', models.CharField(max_length=20)),
                ('recommendation', models.CharField(max_length=100)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CarPDI.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='Documentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=50)),
                ('remark', models.CharField(max_length=200)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CarPDI.vehicle')),
            ],
        ),
    ]
