# Generated by Django 5.2 on 2025-05-30 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarPDI', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='make',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='maker',
            field=models.CharField(choices=[('maruti_suzuki', 'Maruti Suzuki'), ('hyundai', 'Hyundai'), ('tata', 'Tata Motors'), ('mahindra', 'Mahindra'), ('honda', 'Honda'), ('toyota', 'Toyota'), ('kia', 'Kia'), ('skoda', 'Skoda'), ('volkswagen', 'Volkswagen'), ('renault', 'Renault'), ('mg', 'MG Motor'), ('nissan', 'Nissan'), ('jeep', 'Jeep'), ('bmw', 'BMW'), ('audi', 'Audi'), ('mercedes', 'Mercedes-Benz'), ('others', 'Others')], default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='airbags',
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='engine_type',
            field=models.CharField(choices=[('petrol', 'Petrol'), ('diesel', 'Diesel'), ('cng', 'CNG'), ('electric', 'Electric'), ('hybrid', 'Hybrid'), ('mild_hybrid', 'Mild Hybrid'), ('turbo_petrol', 'Turbo Petrol'), ('turbo_diesel', 'Turbo Diesel')], max_length=100),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='fuel_type',
            field=models.CharField(choices=[('petrol', 'Petrol'), ('diesel', 'Diesel'), ('cng', 'CNG'), ('electric', 'Electric'), ('hybrid', 'Hybrid')], max_length=20),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='transmission',
            field=models.CharField(choices=[('manual', 'Manual'), ('automatic', 'Automatic'), ('amt', 'AMT'), ('cvt', 'CVT'), ('dct', 'DCT')], max_length=20),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vin',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
