# Generated by Django 5.2 on 2025-06-05 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarPDI', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='new_car',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicle',
            name='old_car',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
