# Generated by Django 5.2 on 2025-05-31 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarPDI', '0002_remove_vehicle_make_vehicle_maker_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='phone',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicle',
            name='image',
            field=models.ImageField(default=1, upload_to='cars'),
            preserve_default=False,
        ),
    ]
