# Generated by Django 5.2 on 2025-06-06 10:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarPDI', '0002_vehicle_new_car_vehicle_old_car'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='inspected_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspected_vehicles', to=settings.AUTH_USER_MODEL),
        ),
    ]
