# Generated by Django 5.2 on 2025-06-10 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CarPDI', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='maker',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='new_car',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='old_car',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='variant',
        ),
        migrations.DeleteModel(
            name='VehicleMaker',
        ),
    ]
