# Generated by Django 5.2 on 2025-06-03 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarPDI', '0003_customer_email_customer_phone_vehicle_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flushgap',
            name='action',
        ),
        migrations.AddField(
            model_name='fluidlevel',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fluidlevel',
            name='status',
            field=models.CharField(choices=[('all_okay', 'All Okay'), ('not_okay', 'Not Okay')], default='all_okay', max_length=20),
        ),
        migrations.AddField(
            model_name='flushgap',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='flushgap',
            name='status',
            field=models.CharField(choices=[('all_okay', 'All Okay'), ('not_okay', 'Not Okay')], default='all_okay', max_length=20),
        ),
        migrations.AddField(
            model_name='glasscomponent',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='glasscomponent',
            name='status',
            field=models.CharField(choices=[('all_okay', 'All Okay'), ('not_okay', 'Not Okay')], default='all_okay', max_length=20),
        ),
        migrations.AddField(
            model_name='interiorcomponent',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interiorcomponent',
            name='status',
            field=models.CharField(choices=[('all_okay', 'All Okay'), ('not_okay', 'Not Okay')], default='all_okay', max_length=20),
        ),
        migrations.AddField(
            model_name='networksystem',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='networksystem',
            name='status',
            field=models.CharField(choices=[('all_okay', 'All Okay'), ('not_okay', 'Not Okay')], default='all_okay', max_length=20),
        ),
        migrations.AddField(
            model_name='performancecheck',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rubbercomponent',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rubbercomponent',
            name='status',
            field=models.CharField(choices=[('all_okay', 'All Okay'), ('not_okay', 'Not Okay')], default='all_okay', max_length=20),
        ),
        migrations.AddField(
            model_name='systemcheck',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tyrecondition',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tyrecondition',
            name='status',
            field=models.CharField(choices=[('all_okay', 'All Okay'), ('not_okay', 'Not Okay')], default='all_okay', max_length=20),
        ),
        migrations.AlterField(
            model_name='performancecheck',
            name='status',
            field=models.CharField(choices=[('all_okay', 'All Okay'), ('not_okay', 'Not Okay')], default='all_okay', max_length=20),
        ),
        migrations.AlterField(
            model_name='systemcheck',
            name='status',
            field=models.CharField(choices=[('all_okay', 'All Okay'), ('not_okay', 'Not Okay')], default='all_okay', max_length=20),
        ),
    ]
