# Generated by Django 5.2 on 2025-06-03 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarPDI', '0004_remove_flushgap_action_fluidlevel_comments_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fluidlevel',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='fluidlevel',
            name='status',
        ),
        migrations.RemoveField(
            model_name='flushgap',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='flushgap',
            name='status',
        ),
        migrations.RemoveField(
            model_name='glasscomponent',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='glasscomponent',
            name='status',
        ),
        migrations.RemoveField(
            model_name='interiorcomponent',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='interiorcomponent',
            name='status',
        ),
        migrations.RemoveField(
            model_name='networksystem',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='networksystem',
            name='status',
        ),
        migrations.RemoveField(
            model_name='performancecheck',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='rubbercomponent',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='rubbercomponent',
            name='status',
        ),
        migrations.RemoveField(
            model_name='systemcheck',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='tyrecondition',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='tyrecondition',
            name='status',
        ),
        migrations.AddField(
            model_name='flushgap',
            name='action',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='performancecheck',
            name='status',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='systemcheck',
            name='status',
            field=models.CharField(default='All OK', max_length=20),
        ),
    ]
