# Generated by Django 5.2 on 2025-06-06 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_verified_by_admin',
            field=models.BooleanField(default=False),
        ),
    ]
