# Generated by Django 5.2 on 2025-05-30 07:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permissions',
            fields=[
                ('code', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('status', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Roles_Permissions',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PermissionForRole', to='User.permissions')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='RolePermission', to='User.roles')),
            ],
        ),
    ]
